#!/usr/bin/env python3
"""Generate a GitHub Actions workflow that produces Docker images for a target
deployment platform and packs them into a single TGZ artifact.

Build mode : build ONE image from a Dockerfile path (default ./Dockerfile).
Pull mode  : docker compose file (default ./docker-compose.yml); every
             image-only service is pulled for the target platform, every
             build: service is built; build-only services are auto-named
             <image_name>:<image_tag> with -1/-2/... suffixes on collision.
Artifacts  : <repo>_<amd64|arm64>_docker-images.tgz  (ALL images, one TGZ)
             <repo>_<amd64|arm64>_docker-images.tgz.sha256 (separate artifact)
Summary    : the workflow renders a full Action Summary (configuration, image
             list with sizes, archive size + SHA256, offline restore guide).

Usage:
  python generate_workflow.py --repo-name myrepo [--build-mode build|pull]
      [--platform linux/amd64|linux/arm64] [--dockerfile Dockerfile]
      [--compose-file docker-compose.yml] [--image-name myrepo]
      [--image-tag latest] [--output PATH] [--force] [--stdout]
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

PLATFORMS = ("linux/amd64", "linux/arm64")
MODES = ("build", "pull")

WORKFLOW_TEMPLATE = r'''# Generated by the WorkBuddy skill `docker-images-tgz-action`.
# Builds (Dockerfile) or pulls (docker compose) Docker images for a target
# deployment platform, packs ALL of them into ONE TGZ artifact (+ a separate
# SHA256 artifact), and renders a full Action Summary.
# Regenerate via the skill, or edit by hand - both are fine.

name: Docker Images TGZ

on:
  workflow_dispatch:
    inputs:
      platform:
        description: Target deployment server platform
        type: choice
        options:
          - linux/amd64
          - linux/arm64
        default: @DEFAULT_PLATFORM@
        required: true
      build_mode:
        description: "build = build image from a Dockerfile; pull = pull + build all services from a compose file"
        type: choice
        options:
          - build
          - pull
        default: @DEFAULT_MODE@
        required: true
      dockerfile:
        description: "Dockerfile path, relative to repo root (build mode)"
        type: string
        default: "@DEFAULT_DOCKERFILE@"
        required: false
      compose_file:
        description: "Docker compose file path, relative to repo root (pull mode)"
        type: string
        default: "@DEFAULT_COMPOSE@"
        required: false
      compose_profiles:
        description: "Space-separated compose profiles to enable (pull mode, optional)"
        type: string
        default: ""
        required: false
      image_name:
        description: "Image name assigned to image(s) built without one (default = repo name)"
        type: string
        default: "@DEFAULT_IMAGE_NAME@"
        required: false
      image_tag:
        description: "Tag assigned to the image(s) above (default = latest)"
        type: string
        default: "@DEFAULT_IMAGE_TAG@"
        required: false

permissions:
  contents: read

concurrency:
  group: docker-images-tgz-${{ github.ref }}
  cancel-in-progress: false

jobs:
  pack-images:
    name: Pack Docker images into TGZ
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Cross-arch: needed whenever the target platform is linux/arm64 while
      # the runner (ubuntu-latest) is amd64 - for buildx builds AND for
      # `docker compose build` of build-only services in pull mode.
      - name: Set up QEMU (cross-arch for linux/arm64)
        if: inputs.platform == 'linux/arm64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        if: inputs.build_mode == 'build'
        uses: docker/setup-buildx-action@v3

      - name: Resolve configuration
        id: cfg
        env:
          I_PLATFORM: ${{ inputs.platform }}
          I_MODE: ${{ inputs.build_mode }}
          I_IMAGE_NAME: ${{ inputs.image_name }}
          I_IMAGE_TAG: ${{ inputs.image_tag }}
        run: |
          set -euo pipefail
          ARCH="${I_PLATFORM#linux/}"
          IMAGE_NAME="$(echo "$I_IMAGE_NAME" | tr '[:upper:]' '[:lower:]')"
          REPO="$(basename "$GITHUB_REPOSITORY")"
          ARTIFACT="$(echo "$REPO" | tr '.' '-')"
          {
            echo "platform=$I_PLATFORM"
            echo "arch=$ARCH"
            echo "mode=$I_MODE"
            echo "image_name=$IMAGE_NAME"
            echo "image_tag=$I_IMAGE_TAG"
            echo "repo=$REPO"
            echo "artifact=$ARTIFACT"
          } >> "$GITHUB_OUTPUT"

      - name: Validate inputs & write configuration summary
        env:
          I_MODE: ${{ inputs.build_mode }}
          I_PLATFORM: ${{ inputs.platform }}
          I_DOCKERFILE: ${{ inputs.dockerfile }}
          I_COMPOSE: ${{ inputs.compose_file }}
          I_IMAGE_NAME: ${{ steps.cfg.outputs.image_name }}
          I_IMAGE_TAG: ${{ steps.cfg.outputs.image_tag }}
        run: |
          set -euo pipefail
          if [ "$I_MODE" = "build" ]; then
            if [ ! -f "$I_DOCKERFILE" ]; then
              echo "::error::Dockerfile not found at repo-relative path: $I_DOCKERFILE"
              exit 1
            fi
          else
            if [ ! -f "$I_COMPOSE" ]; then
              echo "::error::Compose file not found at repo-relative path: $I_COMPOSE"
              exit 1
            fi
          fi
          echo "## 🐳 Docker Images TGZ — Configuration" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "| Item | Value |" >> "$GITHUB_STEP_SUMMARY"
          echo "| --- | --- |" >> "$GITHUB_STEP_SUMMARY"
          echo "| Build mode | \`$I_MODE\` |" >> "$GITHUB_STEP_SUMMARY"
          echo "| Target platform | \`$I_PLATFORM\` |" >> "$GITHUB_STEP_SUMMARY"
          if [ "$I_MODE" = "build" ]; then
            echo "| Dockerfile | \`$I_DOCKERFILE\` |" >> "$GITHUB_STEP_SUMMARY"
          else
            echo "| Compose file | \`$I_COMPOSE\` |" >> "$GITHUB_STEP_SUMMARY"
          fi
          echo "| Image name (auto-filled for unnamed builds) | \`$I_IMAGE_NAME\` |" >> "$GITHUB_STEP_SUMMARY"
          echo "| Image tag (auto-filled for unnamed builds) | \`$I_IMAGE_TAG\` |" >> "$GITHUB_STEP_SUMMARY"

      # ── Build mode ────────────────────────────────────────────────────────
      # One image: <image_name>:<image_tag>, built for the target platform.
      - name: Build image (build mode)
        if: inputs.build_mode == 'build'
        env:
          I_PLATFORM: ${{ inputs.platform }}
          I_DOCKERFILE: ${{ inputs.dockerfile }}
          E_IMAGE_NAME: ${{ steps.cfg.outputs.image_name }}
          E_IMAGE_TAG: ${{ steps.cfg.outputs.image_tag }}
        run: |
          set -euo pipefail
          CONTEXT_DIR="$(dirname "$I_DOCKERFILE")"
          echo "🏗️  Building $E_IMAGE_NAME:$E_IMAGE_TAG for $I_PLATFORM from $I_DOCKERFILE"
          docker buildx build \
            --platform "$I_PLATFORM" \
            -f "$I_DOCKERFILE" \
            -t "$E_IMAGE_NAME:$E_IMAGE_TAG" \
            --load \
            "$CONTEXT_DIR"
          echo "$E_IMAGE_NAME:$E_IMAGE_TAG" > images.txt

      # ── Pull mode ─────────────────────────────────────────────────────────
      # Three service classes in the compose file:
      #   1. image-only            -> docker pull --platform <target>
      #   2. build + declared image-> docker compose build, keep declared name
      #   3. build-only            -> docker compose build, auto-named
      #      <image_name>:<image_tag>, collision -> :<tag>-1, :<tag>-2, ...
      - name: Pull & build images (pull mode)
        if: inputs.build_mode == 'pull'
        env:
          I_PLATFORM: ${{ inputs.platform }}
          I_COMPOSE: ${{ inputs.compose_file }}
          I_PROFILES: ${{ inputs.compose_profiles }}
          E_IMAGE_NAME: ${{ steps.cfg.outputs.image_name }}
          E_IMAGE_TAG: ${{ steps.cfg.outputs.image_tag }}
        run: |
          set -euo pipefail
          CF="$I_COMPOSE"
          [ -f "$CF" ] || { echo "::error::Compose file not found: $CF"; exit 1; }

          PROFILE_ARGS=()
          for p in $I_PROFILES; do PROFILE_ARGS+=(--profile "$p"); done
          CF_DIR="$(dirname "$CF")"
          ENV_ARGS=()
          if [ -f "$CF_DIR/.env" ]; then ENV_ARGS=(--env-file "$CF_DIR/.env"); fi

          dc() { docker compose "${PROFILE_ARGS[@]}" "${ENV_ARGS[@]}" -f "$CF" "$@"; }

          dc config --format json > compose.resolved.json
          PROJECT="$(jq -r '.name' compose.resolved.json)"

          PULL_SVCS="$(jq -r '[.services | to_entries[] | select(.value.build == null) | .key] | join(" ")' compose.resolved.json)"
          BUILD_SVCS="$(jq -r '[.services | to_entries[] | select(.value.build != null) | .key] | join(" ")' compose.resolved.json)"
          BUILD_ONLY_SVCS="$(jq -r '.name as $p | [.services | to_entries[] | select(.value.build != null) | select(.value.image == null or .value.image == "\($p)-\(.key)") | .key] | join(" ")' compose.resolved.json)"

          echo "## 🔍 Compose services ($PROJECT)" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "| Class | Services |" >> "$GITHUB_STEP_SUMMARY"
          echo "| --- | --- |" >> "$GITHUB_STEP_SUMMARY"
          echo "| pull (image only) | ${PULL_SVCS:-—} |" >> "$GITHUB_STEP_SUMMARY"
          echo "| build + declared image | $(echo "$BUILD_SVCS" | tr ' ' '\n' | grep -vxFf <(echo "$BUILD_ONLY_SVCS" | tr ' ' '\n' | grep .) 2>/dev/null | tr '\n' ' ' || echo —) |" >> "$GITHUB_STEP_SUMMARY"
          echo "| build-only (auto-named) | ${BUILD_ONLY_SVCS:-—} |" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"

          : > images.txt

          # 1) pull image-only services for the TARGET platform
          #    (compose pull cannot pin a platform, so pull per image)
          for svc in $PULL_SVCS; do
            IMG="$(jq -r --arg s "$svc" '.services[$s].image' compose.resolved.json)"
            echo "⬇️  Pulling $IMG ($I_PLATFORM)"
            docker pull --platform "$I_PLATFORM" "$IMG"
            echo "$IMG" >> images.txt
          done

          # 2) build buildable services (cross-arch via QEMU + DOCKER_DEFAULT_PLATFORM)
          if [ -n "$BUILD_SVCS" ]; then
            DOCKER_DEFAULT_PLATFORM="$I_PLATFORM" dc build $BUILD_SVCS
            IDX=0
            for svc in $BUILD_SVCS; do
              DECLARED="$(jq -r --arg s "$svc" '.services[$s].image // ""' compose.resolved.json)"
              GENERATED="${PROJECT}-${svc}"
              if [ -n "$DECLARED" ] && [ "$DECLARED" != "$GENERATED" ]; then
                # service declared its own image name -> keep it
                echo "$DECLARED" >> images.txt
              else
                # build-only service -> auto-fill <image_name>:<image_tag>(-N)
                if [ "$IDX" -eq 0 ]; then
                  TARGET="$E_IMAGE_NAME:$E_IMAGE_TAG"
                else
                  TARGET="$E_IMAGE_NAME:$E_IMAGE_TAG-$IDX"
                fi
                echo "🏷️  Tagging $GENERATED -> $TARGET"
                docker tag "$GENERATED" "$TARGET"
                echo "$TARGET" >> images.txt
                IDX=$((IDX + 1))
              fi
            done
          fi

          sort -u images.txt -o images.txt
          echo "Images to pack:"
          cat images.txt

      # ── Package (both modes) ──────────────────────────────────────────────
      - name: Pack all images into one TGZ
        env:
          E_REPO: ${{ steps.cfg.outputs.repo }}
          E_ARCH: ${{ steps.cfg.outputs.arch }}
        run: |
          set -euo pipefail
          mapfile -t IMAGES < images.txt
          if [ "${#IMAGES[@]}" -eq 0 ]; then
            echo "::error::No images collected - nothing to pack"
            exit 1
          fi

          TGZ="${E_REPO}_${E_ARCH}_docker-images.tgz"
          mkdir -p dist
          echo "📦 Packing ${#IMAGES[@]} image(s) -> dist/$TGZ"
          docker save "${IMAGES[@]}" | gzip > "dist/$TGZ"
          gzip -t "dist/$TGZ"

          SHA="$(sha256sum "dist/$TGZ" | awk '{print $1}')"
          SIZE="$(du -h "dist/$TGZ" | cut -f1)"
          (cd dist && sha256sum "$TGZ" > "$TGZ.sha256")

          echo "### 📦 Packaging result" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "| Item | Value |" >> "$GITHUB_STEP_SUMMARY"
          echo "| --- | --- |" >> "$GITHUB_STEP_SUMMARY"
          echo "| Archive | \`$TGZ\` |" >> "$GITHUB_STEP_SUMMARY"
          echo "| Size | $SIZE |" >> "$GITHUB_STEP_SUMMARY"
          echo "| SHA256 | \`$SHA\` |" >> "$GITHUB_STEP_SUMMARY"
          echo "| Images inside | ${#IMAGES[@]} |" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "#### Images" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "| Image | Size |" >> "$GITHUB_STEP_SUMMARY"
          echo "| --- | --- |" >> "$GITHUB_STEP_SUMMARY"
          for img in "${IMAGES[@]}"; do
            ISZ="$(docker image inspect "$img" --format '{{.Size}}' | numfmt --to=iec)"
            echo "| \`$img\` | $ISZ |" >> "$GITHUB_STEP_SUMMARY"
          done

      - name: Upload TGZ artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.cfg.outputs.artifact }}_${{ steps.cfg.outputs.arch }}_docker-images
          path: dist/*.tgz
          if-no-files-found: error

      - name: Upload SHA256 artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.cfg.outputs.artifact }}_${{ steps.cfg.outputs.arch }}_docker-images-sha256
          path: dist/*.sha256
          if-no-files-found: error

      - name: Summary — artifacts & restore guide
        env:
          E_REPO: ${{ steps.cfg.outputs.repo }}
          E_ARCH: ${{ steps.cfg.outputs.arch }}
          E_ARTIFACT: ${{ steps.cfg.outputs.artifact }}
        run: |
          set -euo pipefail
          TGZ="${E_REPO}_${E_ARCH}_docker-images.tgz"
          SHA_FILE="${TGZ}.sha256"
          echo "### 📥 Artifacts" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "Download both from this run's **Artifacts** section:" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "- \`${E_ARTIFACT}_${E_ARCH}_docker-images\` — the single TGZ \`${TGZ}\` containing **all** images produced by this run" >> "$GITHUB_STEP_SUMMARY"
          echo "- \`${E_ARTIFACT}_${E_ARCH}_docker-images-sha256\` — checksum file \`${SHA_FILE}\`" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "### ♻️ Offline restore on the target server" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo '```bash' >> "$GITHUB_STEP_SUMMARY"
          echo "# 1) verify integrity" >> "$GITHUB_STEP_SUMMARY"
          echo "sha256sum -c $SHA_FILE" >> "$GITHUB_STEP_SUMMARY"
          echo "# 2) load all images into the local Docker daemon" >> "$GITHUB_STEP_SUMMARY"
          echo "docker load -i $TGZ" >> "$GITHUB_STEP_SUMMARY"
          echo "# 3) verify" >> "$GITHUB_STEP_SUMMARY"
          echo "docker images" >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
'''


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Render the 'Docker Images TGZ' GitHub Actions workflow for a repository."
    )
    p.add_argument("--repo-name", required=True,
                   help="Repository name (GitHub repo, e.g. 'my-app'); drives artifact naming "
                        "and the default image name.")
    p.add_argument("--build-mode", choices=MODES, default="build",
                   help="Default workflow mode: 'build' (Dockerfile) or 'pull' (compose). Default: build")
    p.add_argument("--platform", choices=PLATFORMS, default="linux/amd64",
                   help="Default target platform. Default: linux/amd64")
    p.add_argument("--dockerfile", default="Dockerfile",
                   help="Default Dockerfile path, repo-relative (build mode). Default: Dockerfile")
    p.add_argument("--compose-file", default="docker-compose.yml",
                   help="Default compose file path, repo-relative (pull mode). Default: docker-compose.yml")
    p.add_argument("--image-name", default=None,
                   help="Default image name for image(s) built without one. Default: repo name, lowercased")
    p.add_argument("--image-tag", default="latest",
                   help="Default tag for the image(s) above. Default: latest")
    p.add_argument("--output", default=None,
                   help="Output file path. Default: <cwd>/.github/workflows/docker-images.yml")
    p.add_argument("--force", action="store_true",
                   help="Overwrite the output file if it already exists.")
    p.add_argument("--stdout", action="store_true",
                   help="Print the rendered workflow to stdout instead of writing a file.")
    return p


def sanitize_repo(name: str) -> str:
    """Repo name -> safe default docker image name component (lowercase)."""
    s = name.strip().lower()
    s = re.sub(r"[^a-z0-9._/-]+", "-", s).strip("-._/")
    if not s:
        raise SystemExit(f"error: repo name {name!r} yields an empty image name")
    return s


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)

    repo = args.repo_name.strip()
    if not repo:
        raise SystemExit("error: --repo-name must not be empty")

    for label, path in (("dockerfile", args.dockerfile), ("compose-file", args.compose_file)):
        p = Path(path)
        if p.is_absolute():
            raise SystemExit(
                f"error: --{label} must be relative to the repository root (the workflow "
                f"checks out the repo at the workspace root): {path}"
            )
        if ".." in p.parts:
            raise SystemExit(f"error: --{label} must not escape the repository root: {path}")

    image_name = args.image_name if args.image_name else sanitize_repo(repo)
    if image_name != image_name.lower():
        print(f"warning: image name lowercased -> {image_name.lower()}", file=sys.stderr)
        image_name = image_name.lower()

    if not re.fullmatch(r"[a-z0-9]+(?:(?:\.|_|__|-+)[a-z0-9]+)*(?::[0-9]+)?(?:/[a-z0-9]+(?:(?:\.|_|__|-+)[a-z0-9]+)*)*", image_name):
        print(f"warning: image name {image_name!r} does not match docker naming rules", file=sys.stderr)

    workflow = WORKFLOW_TEMPLATE
    for token, value in (
        ("@DEFAULT_PLATFORM@", args.platform),
        ("@DEFAULT_MODE@", args.build_mode),
        ("@DEFAULT_DOCKERFILE@", args.dockerfile.replace("\\", "/")),
        ("@DEFAULT_COMPOSE@", args.compose_file.replace("\\", "/")),
        ("@DEFAULT_IMAGE_NAME@", image_name),
        ("@DEFAULT_IMAGE_TAG@", args.image_tag),
        ("@REPO_NAME@", repo),
    ):
        workflow = workflow.replace(token, value)

    if "@DEFAULT_" in workflow or "@REPO_NAME@" in workflow:
        raise SystemExit("internal error: unresolved template token(s) remain")

    if args.stdout:
        sys.stdout.write(workflow)
        return 0

    out = Path(args.output) if args.output else Path(".github/workflows/docker-images.yml")
    if out.exists() and not args.force:
        raise SystemExit(f"error: {out} already exists (use --force to overwrite)")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(workflow, encoding="utf-8", newline="\n")

    print(f"✅ Workflow written to: {out}")
    print()
    print("Baked-in defaults (all remain overridable per run in the 'Run workflow' dialog):")
    print(f"  - default build mode : {args.build_mode}")
    print(f"  - default platform   : {args.platform}")
    print(f"  - Dockerfile         : {args.dockerfile}   (build mode)")
    print(f"  - compose file       : {args.compose_file}   (pull mode)")
    print(f"  - image name / tag   : {image_name}:{args.image_tag}")
    print()
    print("Next steps:")
    print("  1. Commit & push the workflow to the target repository.")
    print("  2. Repo -> Actions -> 'Docker Images TGZ' -> Run workflow.")
    print("  3. Download the two artifacts (TGZ + SHA256) from the run page.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
